export const GET_CUSTOMER = "GET_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
export const CUSTOMER_SIGNUP = "CUSTOMER_SIGNUP";
export const RESTAURANT_SIGNUP = "RESTAURANT_SIGNUP";
